#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_USER_OTHER;
    ALTER USER $POSTGRES_USER_OTHER WITH PASSWORD '$POSTGRES_PASSWORD_OTHER';
    CREATE USER $POSTGRES_USER_SNOW;
    ALTER USER $POSTGRES_USER_SNOW WITH PASSWORD '$POSTGRES_PASSWORD_SNOW';
    CREATE DATABASE $DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $POSTGRES_USER_OTHER;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $POSTGRES_USER_SNOW;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL





